# Fully Corrected recipe.yml (v2)
name: douddjs/custom-vos
id: douddjs/custom-vos
stages:
- id: build
  base: ghcr.io/vanilla-os/desktop:main
  singlelayer: false
  labels:
    maintainer: Adham_Ahmad
  args:
    DEBIAN_FRONTEND: noninteractive
  
  runs:
    commands:
      - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

  modules:
  - name: init-setup
    type: shell
    commands:
      - lpkg --unlock
      - apt-get update

  - name: example-packages
    type: apt
    packages:
      - vim

  - name: example-commands
    type: shell
    commands:
      # <<< FIX: Indentation corrected as you pointed out
      - echo Example output

  - name: example-modules
    type: includes
    includes:
      - modules/50-install-debs.yml

  - name: install-snapd
    type: apt
    description: Install snapd and Snap Store
    packages:
      - snapd
      - gnome-software-plugin-snap

  - name: enable-snapd
    type: shell
    description: Enable snapd service
    commands:
      - systemctl enable snapd.service
      - systemctl enable snapd.socket

  - name: davinci-resolve-deps
    type: apt
    description: Install DaVinci Resolve dependencies
    packages:
      - libssl1.1
      - ocl-icd-opencl-dev
      - fakeroot
      - xorriso
      - libxcb-composite0
      - libxcb-cursor0
      - libxcb-damage0
      - libxcb-dpms0
      - libxcb-dri2-0
      - libxcb-dri3-0
      - libxcb-ewmh2
      - libxcb-glx0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-record0
      - libxcb-render0
      - libxcb-res0
      - libxcb-screensaver0
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-sync1
      - libxcb-util1
      - libxcb-xf86dri0
      - libxcb-xfixes0
      - libxcb-xinerama0
      - libxcb-xinput0
      - libxcb-xkb1
      - libxcb-xtest0
      - libxcb-xv0
      - libxcb-xvmc0

  - name: make-resolve-script-executable
    type: shell
    description: Make DaVinci Resolve helper script executable
    commands:
      - chmod +x /usr/local/bin/prepare-davinci-resolve

  - name: remove-prev-fsguard
    type: shell
    commands:
      - rm -rf /FsGuard
      - rm -f ./minisign.pub ./minisign.key
      - chmod +x /usr/sbin/init

  - name: fsguard
    type: fsguard
    CustomFsGuard: false
    FsGuardLocation: "/usr/sbin/FsGuard"
    GenerateKey: true
    FilelistPaths:
      - "/usr/bin"
  
  - name: system-customizations
    type: shell
    description: Update font cache and compile schemas
    commands:
      - fc-cache -fv
      - glib-compile-schemas /usr/share/glib-2.0/schemas/

  - name: set-image-name-abroot
    type: includes
    includes:
      - modules/80-set-image-abroot-config.yml

  - name: cleanup
    type: shell
    commands:
      - apt-get autoremove -y
      - apt-get clean
      - lpkg --lock

  - name: cleanup2
    type: shell
    commands:
      - rm -rf /tmp/*
      - rm -rf /var/tmp/*
      - rm -rf /sources

- id: vanilla-os-desktop
  base: scratch
  from: build